### ISSUE TITLE
doesn't support pylint >= 2

### ISSUE THREAD

**Issue by kzidane** [jschaf/pylint-flask#8]
Looks like the latest `pylint` [requires `astroid>=2.0.0`](https://github.com/PyCQA/pylint/blob/8682a220911a9c22286089e08f7e77b7b15d990b/pylint/__pkginfo__.py#L32) and `pylint-flask` doesn't support that atm. Any plans to fix anytime soon?

```
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/pylint3", line 11, in <module>
    sys.exit(run_pylint())
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pylint/__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pylint/lint.py", line 1315, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pylint/lint.py", line 519, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/astroid/modutils.py", line 196, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/astroid/modutils.py", line 239, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pylint_flask/__init__.py", line 79, in <module>
    MANAGER.register_transform(nodes.From,
AttributeError: module 'astroid.nodes' has no attribute 'From'
```

**Comment by carlio** [comment]
This should just be a case of replacing 'nodes.From' with 'nodes.ImportFrom'? I will try to make a PR soon.

**Comment by antgel** [comment]
This should be closed, as it was merged in PR #9 .

**Comment by jschaf** [comment]
Closing since I think it's done.

**Comment by kzidane** [comment]
Thank you! Appreciate it.
